{% set name = "AmpliconSplitter" %}
{% set version = "1.9.22" %}
{% set sha256 = "b8a220ac17f1e1e69f6f45a315876c597ef90e7e19abff35c1d7d536eb836939" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RolandFaure/AmpliconSplitter/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ampliconsplitter-aarch64.patch

build:
  number : 0
  run_exports:
    - {{ pin_subpackage("ampliconsplitter", max_pin="x.x") }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libcxx <18 # [osx]
  host:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - python
    - scipy
    - numpy
    - minimap2
    - minigraph >=0.20
    - racon
    - samtools >=1.16
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - raven-assembler

test:
  commands:
    - ampliconsplitter.py --help
    
extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - rolandfaure

about:
  home: https://github.com/RolandFaure/AmpliconSplitter
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Split highly similar collapsed amplicons to obtain all amplicons from a sample"
  maintainer : RolandFaure # Optional
